
# Solo imprimir verticalmente
def funcion_barra(n):

      if n == 0:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('+-+')
      elif n == 1:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('+-+')
      elif n == 2:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 3:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 4:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 5:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 6:
            print('+-+')
            print('| |')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 7:
            print('+-+')
            print('| |')
            print('| |')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 8:
            print('+-+')
            print('| |')
            print('xxx')
            print('xxx')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      elif n == 9:
            print('+-+')
            print('xxx')
            print('xxx')
            print('xxx')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('XXX')
            print('+-+')
      else:
            print('ingrese correctamente')
      

while True:
      n = int(input('ingrese un numero: '))
      #print("{}{}".format(funcion_barra(n), funcion_barra(n)))
      print(funcion_barra(n), end= " ")
     
      funcion_barra(n)